---
- name: Generate NTP Config
  hosts: arista_ceos
  gather_facts: false
  tasks:
    - name: Create Configs Directory
      ansible.builtin.file:
        path: configs 
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Create NTP Configuration
      ansible.builtin.template:
        src: templates/arista_ceos.j2
        dest: configs/{{ inventory_hostname }}.cfg
      delegate_to: localhost