---
interfaces:
  
  Management0:
    description: Management Interface
    ip_address: "192.168.100.12/24"

  Ethernet1:
    ip_address: "172.31.1.1/31"
    description: "LEAF-TO-CORE-01"
  
  Ethernet2:
    vlan: 10
    description: "LEAF-TO-CLIENT2"
  
  Vlan10:
    ip_address: "192.168.20.254/24"
    description: "VLAN 10"
  
  Loopback0:
    ip_address: "10.100.1.1/32"
    description: "Loopback for Router ID"

bgp:
  asn: 65001
  peer_groups:
    underlay:
      - peer: ceos-01
        ip_address: 172.31.1.0
        remote_as: 65100

    overlay:
      - peer: ceos-01
        ip_address: 10.100.1.254
        remote_as: 65100