---
interfaces:

  Management0:
    description: Management Interface      
    ip_addr: "192.168.100.11/24"

  Ethernet1:
    ip_address: "172.31.1.4/31"
    description: "SPINE-TO-CORE-01"
  
  Ethernet2:
    ip_address: "172.31.1.6/31"
    description: "SPINE-TO-CORE-02"

  Ethernet3:
    ip_address: "172.31.1.0/31"
    description: "SPINE-TO-LEAF-CEOS-02"
  
  Ethernet4:
    ip_address: "172.31.1.2/31"
    description: "SPINE-TO-LEAF-CEOS-03"

  Loopback0:
    ip_address: "10.100.1.254/32"
    description: "Loopback for Router ID"

bgp:
  asn: 65100
  peer_groups:
    underlay:
      - peer: ceos-02
        ip_address: 172.31.1.1
        remote_as: 65001
      - peer: ceos-03
        ip_address: 172.31.1.3
        remote_as: 65002
    overlay:
      - peer: ceos-02
        ip_address: 10.100.1.1
        remote_as: 65001
      - peer: ceos-03
        ip_address: 10.100.1.2
        remote_as: 65002

    core:
      - peer: core-01
        ip_address: 172.31.1.5
        remote_as: 65400
      - peer: core-02
        ip_address: 172.31.1.7
        remote_as: 65400