---
interfaces:

  Management0:
    description: Management Interface
    ip_addr: "192.168.100.13/24"
        
  Ethernet1:
    ip_address: "172.31.1.3/31"
    description: "LEAF-TO-CORE-01"
  
  Vlan10:
    ip_address: "192.168.20.254/24"
    description: "VLAN 10"

  Loopback0:
    ip_address: "10.100.1.2/32"
    description: "Loopback for Router ID"

bgp:
  asn: 65002
  peer_groups:
    underlay:
      - peer: ceos-01
        ip_address: 172.31.1.2
        remote_as: 65100

    overlay:
      - peer: ceos-01
        ip_address: 10.100.1.254
        remote_as: 65100