---

- name: Validate Collection is working
  gather_facts: false
  connection: ansible.netcommon.network_cli
  hosts: arista_ceos
  tasks:
    - name: Run a command on ARISTA EOS
      arista.eos.eos_command:
        commands: "show version"
      register: eos_output

    - name: Display the EOS output 
      debug:
        var: eos_output