---
- name: Create New User with ansible
  hosts: arista_ceos
  tasks:

    - name: Update the admin user adding public key auth
      arista.eos.eos_user:
        name: admin
        sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        role: network-admin
        state: present
